steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/niveus-research-project/sampleapp:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/niveus-research-project/sampleapp:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'sampleapp'
   - '--image'
   - 'gcr.io/niveus-research-project/sampleapp:$COMMIT_SHA'
   - '--region'
   - 'ap-south1'
   - '--platform'
 - name: gcr.io/cloud-builders/gcloud
   args: [ 'compute', 'instance-groups', 'managed', 'rolling-action', 'restart', 'ig-poc-jssample', '--region=ap-south1' ]
 images:
   - 'gcr.io/niveus-research-project/sampleapp:$COMMIT_SHA'
